### ISSUE TITLE
Data model for tile-qa files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#114]
Please review the data model for the tile-qa files in the tiles directories.

The structural description of these files should be complete, but descriptions of the HDUs, header keywords and columns need work. If necessary it is possible for files to refer to other files, or for HDUs to refer to other HDUs, to reduce duplication of effort.

**Comment by araichoor** [comment]
Hi @weaverba137 ,

I m starting to give a look at this one.

One remark already: I notice that it is written in the top summary that such `tile-qa*fits` files "_are only associated with cumulative tile coadds._"
That is correct for our daily reductions; though, for data releases, it also exists for other GROUPIDs: spot-checking for a couple of tiles in fuji and guadalupe, this file also exists for the `pernight` reductions.
I don't know what is the plan for the next data releases (@sbailey?).

I'll add this information in the "Notes and examples" section, but I'm mentioning here in case this requires other changes in the documentation organization (maybe not, but I m not sure).

**Comment by araichoor** [comment]
Thanks, I've done that.

A couple of further questions:

The PETALQA extension of the `tile-qa*fits` files is very similar to the PETALQA extension of the `exposure-qa*fits` files (it s basically the mean of those files); though I see that this has not been filled: https://github.com/desihub/desidatamodel/blob/main/doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/exposure-qa-EXPID.rst
=> shall I go ahead, and edit `exposure-qa-EXPID.rst` in my PR, so that both are "tied" (i.e. changes will be consistent) ?

Unrelated to that: I thought it might be useful to provide the code link to the definition of the bits used in the `QAFIBERSTATUS` column; is that possible? if so, what link shall I provide? the current "master" link is:
https://github.com/desihub/desispec/blob/720153babcf85dd93530252b0c1f631d48edfc0d/py/desispec/maskbits.py#L53-L81

Thanks!

**Comment by sbailey** [comment]
@araichoor if you can fill in the exposure-qa-EXPID.rst PETALQA table, that would be very helpful.  Julien is traveling today so won't be updating it.

Mask bits: please link to the top-level doc/bitmasks.rst file which is where we are supposed to fill in the details of QAFIBERSTATUS, etc., including links to the code/config files that define them.  that file is currently nearly blank, but that's supposed to be the reference bitmask definition location.

**Comment by araichoor** [comment]
ok perfect, thanks!

**Comment by weaverba137** [comment]
Closed by #132.
