### ISSUE TITLE
Next steps for maskbit documentation in desidatamodel

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#140]
#139 provided a set of links to mask bit definitions in several packages (thank you!). Based on discussions on 2023-01-31, there are additional documentation tasks we may want to consider:

* Incorporate mask bit definitions into the data model, beyond just links.
  - At least some of the links are to YAML files, it might be easier for people to read in RST/HTML format.
  - desitarget mask bits will be documented extensively in the EDR paper, so might be easier to just link to those.
  - Additional effort might be required to keep the definitions in sync, but hopefully the mask bit definitions being considered are reasonably stable.
* Add links to examples of using mask bits.
  - These examples could be in the high-level documentation or a tutorial or somewhere else, but the links should exist.

@sbailey, @forero, I think this captures the discussion today. Please comment as needed.

**Comment by geordie666** [comment]
An additional note that was mentioned today:

-  The `ZWARN` bitmask is more expansive [in desitarget](https://github.com/desihub/desitarget/blob/2.4.0/py/desitarget/data/targetmask.yaml#L230) than it is [in redrock](https://github.com/desihub/redrock/blob/0.16.0/py/redrock/zwarning.py#L14). This is because the `desitarget.mtl` code uses some of the bits reserved by `redrock`.
