### ISSUE TITLE
Should RA, Dec descriptions include J2000?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#147]
Now that we have standard column descriptions for columns like RA, Dec and similar coordinates, should that description include J2000 to denote the epoch, or possibly some other epoch?

**Comment by weaverba137** [comment]
@sbailey, this question fell through the cracks. If you don't know the answer of the top of your head, feel free to reassign to someone else.

**Comment by sbailey** [comment]
For targets, we should *not* specify J2000 in the column descriptions, because we have a separate `REF_EPOCH` column that specifies the per-target epoch to use for proper motions, and in most cases that is the Gaia reference epoch of 2015.5, not J2000.

For TILERA, TILEDEC we should also not specify J2000 because those don't have proper motion and the concept of *epoch* isn't needed.  And for real coordinate aficionados, we are tied to the Gaia Celestial Reference Frame 2, which is ICRS tied to Gaia, for which the concept of *equinox* also doesn't apply.

Do you agree, @geordie666 ?

**Comment by geordie666** [comment]
The equinox of the targets [is tied to Gaia](https://www.legacysurvey.org/dr9/description/#astrometry), and Gaia is on the ICRS. Strictly, the ICRS is ambivalent as regards equinox — but the ICRS _is_ [very, very close to J2000](https://www.cosmos.esa.int/web/gaia/faqs#ICRSICRF), by design.

Because targets adopt the same convention as for the Legacy Surveys sweep files, targets most often have a `REF_EPOCH` of zero, which effectively just means that a source has no measured proper motion.

So, I'm mildly concerned that if we _don't_ quote any equinox at all, we'll get questions about what equinox is appropriate for these `REF_EPOCH=0` sources.

Perhaps we're close enough to an equinox of J2000 for all Legacy Surveys sources that we should just quote J2000 as the equinox for all target coordinates, as we did in the documentation for the [original source catalogs](https://www.legacysurvey.org/dr9/catalogs/). Alternatively, we could explicitly state that we've adopted the ICRS. Either way, we should then separately note that `REF_EPOCH` refers to the epoch for proper motion measurements rather than the equinox.

I'm not an expert on astrometry, though (clearly!), so @dstndstn should provide feedback on his preferred course of action.

**Comment by geordie666** [comment]
One more thought. Gaia explicitly states (for RA):

Barycentric right ascension 𝛼 of the source in ICRS at the reference epoch ref_epoch

So, I think, for the targets, we should either state:

Right ascension (J2000)

or:

Barycentric right ascension 𝛼 of the source in the ICRS (tied to Gaia DR2)

I'll let @dstndstn decide which (if he agrees).

**Comment by weaverba137** [comment]
@dstndstn, do you have any further comments on this?

**Comment by dstndstn** [comment]
We're on the Gaia-DR2 system, so I think that implies ICRS.

**Comment by weaverba137** [comment]
I think we've answered the question of what system we are on, but how should we actually phrase that for the purposes of the column description?

**Comment by geordie666** [comment]
I vote for:

Barycentric right ascension 𝛼 of the source in the ICRS 
Barycentric declination 𝛿 of the source in the ICRS

**Comment by sbailey** [comment]
I agree with the spirit of @geordie666 's response, while stripping out unicode and making it shorter to save horizontal space

Barycentric right ascension in ICRS
Barycentric declination in ICRS

"degrees" is important but should already be in the separate units column.  If we want more information about "Gaia-DR2" etc. that could go in separate documentation about DESI astrometry and photometry overall, while keeping these column descriptions short but informative.

**Comment by weaverba137** [comment]
Should this description be applied to every column in the csv file with 'RA' in it or just TARGET_RA, TARGET_DEC and RA, DEC?

**Comment by sbailey** [comment]
I think it is every RA, DEC mention including TILE_RA/DEC, TARGET_RA/DEC, and plain RA/DEC.  I will take an editing pass on the datamodel now and consider if there are any exceptions to that.

**Comment by araichoor** [comment]
sorry if that s irrelevant, but just in case: redrock fibermap extension also has PLATE_{RA,DEC}, MEAN_FIBER_{RA,DEC}, STD_FIBER_{RA,DEC} columns.
