### ISSUE TITLE
Support "see other" functionality at HDU level

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#89]
Currently there is a way to say "this data model is the same as this other data model", but it would be nice to have this functionality at the HDU level, not just the file level.

**Comment by weaverba137** [comment]
Sphinx makes it slightly tricky to cross-reference *sections* within another document.  There are two options:

1. Create an explicit label for an HDU in one document and use `:ref:` to refer to it.
2. Use "bare" RST notation: `.. _link: ../foo/bar/file.html#hdu5`.

Finally, note that we already have the functionality to say "this HDU is the same as another HDU" within the *same* document.  This is already used in the `desi-EXPID.rst` raw data model since there are 30 HDUs that differ only in name.

**Comment by weaverba137** [comment]
This will be implemented in #102.  The format is, *e.g.*:
```
HDU5
----

See `HDU2 in some other file <../../some-other-file.html#hdu2>`_.
```

**Comment by sbailey** [comment]
That looks like a nice clean syntax.  What do you suggest for the FIBERMAP HDU, which gains columns as it is propagated through the various steps of the pipeline, and then at the coadd stage gets split into FIBERMAP and EXP_FIBERMAP?  If we were only writing text for humans to read and not auto-parsing for data model validation, I would document this as something like:

> The cframe FIBERMAP HDU is the same as the FIBERMAP HDU in (reference original fibermap file) with the following additional columns: (add a table with those columns).

but that would be tricky to algorithmically support.  Suggestions?

Given that our file formats prioritize EXTNAME over extension number, could we move the data model to be EXTNAME-centric instead of extension number centric?  e.g. in the raw data the order of the camera HDUs really is essentially random, and in the spectra (or coadds?) the SCORES HDU recently moved number as part of a refactor, changing the numbering of all of the other HDUs too.  I'd rather than the documentation (and cross-links like this) emphasize that people should be using EXTNAME, not reading by number.

**Comment by weaverba137** [comment]
Sure, this is late-breaking news, but I've also been developing a way to mark columns as optional (#86).

The code already prefers EXTNAME over extension number (#74), to support the idea that extensions could have varying order. I have *not* yet developed a way to mark entire HDUs as optional, but that case is relatively rare.  However, I am starting to see evidence that given the same type of file, with the same number of HDUs, the EXTNAME can *vary*, and that is going to be painful do deal with.
